### ISSUE TITLE
extract files without an extension

### ISSUE THREAD

**Issue by roman2git** [davidesner/keboola-ftp-extractor#2]
Hello, 

I tried to use keboola-ftp-extractor and faced an issue when the file have no extension. Even more - file name contain a dot. So it looks like "name_of_something.18060201" where part after dot is changeable.

I still didn't find a way to load files with 'Download Folder' option, when I keep the 'extension' empty - I get nothing because of '.csv' as default at the same time I can't put anything into 'extension' because that doesn't exist. And unfortunately I can't change  filenames - that is out of my control.

Is it possible to modify the extractor to be able put '*' in 'extension' which would means 'any or empty' or make some parameter: 'don't check extension' and check the file prefix only?

Thank you.

**Comment by davidesner** [comment]
Hi,

thank you for noticing. This is a useful function indeed. I have implemented support of the wildcard `*` in the `extension` field. If specified, the extension will be ignored, i.e. any extension will be accepted. The documentation is updated accordingly.

**Comment by roman2git** [comment]
Hello,
That works perfect. 

Thank you a lot!
