### ISSUE TITLE
Folder is removed from state if no files were fetched

### ISSUE THREAD

**Issue by Halama** [davidesner/keboola-ftp-extractor#3]
How to simulated:
- incremental fetching with Continue since last run = `true`
- add few files to FTP
- run extraction (all files are downloaded) OK
- run extraction again (0 files are download) OK - Folder is removed from `visitedFolders` in `state` file
- run extraction againg (all files are donwloaded again) NOT OK 

https://github.com/davidesner/keboola-ftp-extractor/blob/4f8a2af5ad248fd2fae8167651a23baa635f5e97/src/main/java/keboola/ftp/extractor/Extractor.java#L80

**Comment by davidesner** [comment]
This is fixed now in 74f065246632914db0d5a6e34807237fea3f0eea
